name: Linting

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Node-JS Lint
    runs-on: "ubuntu-latest"
    steps:
      - name: Repository Checkout
        uses: "actions/checkout@v3"

      - name: Setup Node-JS
        uses: "actions/setup-node@v3"
        with:
          node-version: '16'

      - name: npm ci
        run: npm ci

      - name: npm lint
        run: npm run lint